server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.178.128:3306/tensquare_base?characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
